name: Build Pure Stock Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git bc bison flex make gcc g++ \
            clang lld llvm \
            libssl-dev libelf-dev \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            wget unzip file

      - name: Clone Xiaomi Kernel Source
        run: |
          git clone --depth=1 \
          -b light-u-oss \
          https://github.com/MiCode/Xiaomi_Kernel_OpenSource kernel

      # ONLY build fixes. No KernelSU. No config changes.
      - name: Fix missing MIHW
        run: |
          cd kernel
          mkdir -p drivers/mihw
          touch drivers/mihw/Makefile
          sed -i '/mihw/d' drivers/Makefile || true
          sed -i '/mihw/d' drivers/Kconfig || true

      - name: Build Stock Kernel
        run: |
          cd kernel

          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-

          make O=out light_defconfig

          make -j$(nproc) \
            O=out \
            ARCH=arm64 \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            Image.gz

      - name: Download boot.img
        run: |
          wget -O boot.img \
          https://github.com/testuru56-del/Stock-kernel/releases/download/Boot/boot.img

      - name: Download Magisk
        run: |
          wget -O Magisk.apk \
          https://github.com/topjohnwu/Magisk/releases/download/v30.3/Magisk-v30.3.apk

          unzip -p Magisk.apk lib/x86_64/libmagiskboot.so > magiskboot
          chmod +x magiskboot

      - name: Repack boot
        run: |
          mkdir work

          cp boot.img work/
          cp kernel/out/arch/arm64/boot/Image.gz work/
          cp magiskboot work/

          cd work

          ./magiskboot unpack boot.img

          cp Image.gz kernel

          ./magiskboot repack boot.img

          ls -lah

      - name: Upload boot
        uses: actions/upload-artifact@v4
        with:
          name: Stock-Boot-Test
          path: work/new-boot.img
