name: Repack Boot

on:
  workflow_dispatch:

jobs:
  repack:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget unzip file

      - name: Download files
        run: |
          wget -O boot.img https://github.com/USERNAME/REPO/releases/download/boot/boot.img
          wget -O Image.gz https://github.com/USERNAME/REPO/releases/download/boot/Image.gz

      - name: Verify
        run: |
          file boot.img
          file Image.gz
          ls -lh

      - name: Download Magisk APK
        run: |
          wget -O Magisk.apk https://github.com/topjohnwu/Magisk/releases/download/v29.0/Magisk-v29.0.apk
          unzip -p Magisk.apk lib/x86_64/libmagiskboot.so > magiskboot
          chmod +x magiskboot

      - name: Unpack
        run: |
          mkdir work
          cp boot.img work/
          cp Image.gz work/
          cp magiskboot work/

          cd work
          ./magiskboot unpack boot.img

          ls -lah
          file *

      - name: Replace Kernel
        run: |
          cp Image.gz work/kernel

      - name: Repack
        run: |
          cd work
          ./magiskboot repack boot.img

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: patched_boot
          path: work/new-boot.img
