name: Repack Boot Image

on:
  workflow_dispatch:

jobs:
  repack:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip file

      - name: Download boot.img
        run: |
          wget -O boot.img \
          https://github.com/testuru56-del/Stock-kernel/releases/download/Boot/boot.img

      - name: Download Image.gz
        run: |
          wget -O Image.gz \
          https://github.com/testuru56-del/Stock-kernel/releases/download/Boot/Image.gz

      - name: Download Magisk
        run: |
          wget -O Magisk.apk \
          https://github.com/topjohnwu/Magisk/releases/download/v30.7/Magisk-v30.7.apk

      - name: Extract magiskboot
        run: |
          unzip -p Magisk.apk lib/x86_64/libmagiskboot.so > magiskboot
          chmod +x magiskboot

      - name: Verify files
        run: |
          ls -lh
          file boot.img
          file Image.gz
          file magiskboot

      - name: Unpack boot image
        run: |
          mkdir work
          cp boot.img work/
          cp Image.gz work/
          cp magiskboot work/

          cd work
          ./magiskboot unpack boot.img

          echo "===== UNPACKED FILES ====="
          ls -lah
          echo "=========================="

      - name: Replace kernel
        run: |
          cp Image.gz work/kernel

      - name: Repack boot image
        run: |
          cd work
          ./magiskboot repack boot.img

      - name: Show output
        run: |
          ls -lah work

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: patched_boot
          path: |
            work/new-boot.img
            work/*
